
name: Feature request
description: Suggest an idea for Perplexity integration.
labels: feature-request
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: Feature description
      description: >-
        A clear and concise description of the feature request.
