name: Release

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: Set package version
        run: |
          version="${{ github.event.release.tag_name }}"
          sed -i 's/^version = ".*"/version = "'"${version}"'"/' pyproject.toml
          cd "${{ github.workspace }}/custom_components/perplexity"
          sed -i "s/\"version\": \".*\"/\"version\": \"${version}\"/" manifest.json

      - name: Create zipped release package
        shell: bash
        run: |
          cd "${{ github.workspace }}/custom_components/perplexity"
          zip perplexity.zip -r ./

      - name: Upload zip to release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228  # v3.0.2
        with:
          files: ${{ github.workspace }}/custom_components/perplexity/perplexity.zip
